### ISSUE TITLE
Support for optional properties for creating a collection 

### ISSUE THREAD

**Issue by StefMa** [ioki-mobility/go-outline#27]
In https://github.com/ioki-mobility/go-outline/pull/17 we added support to create a collection via the api client. But we added only the **required properties** to the request. 

This issues is here to add all the possible **optional properties** to the api client.

**Comment by rsjethani** [comment]
@StefMa IMO you can remove any mention of cli in this ticket and just focus on client API changes. I have added relevant label hope this is okay.
