### ISSUE TITLE
Do we need a `ParentDocumentId` type?

### ISSUE THREAD

**Issue by StefMa** [ioki-mobility/go-outline#31]
Mentiond here https://github.com/ioki-mobility/go-outline/pull/20#discussion_r1282205239

Do we need this type?
Does it make sense to simly re-use `Documentd` but naming it `ParentDocumentId` in code? 🤔

**Comment by rsjethani** [comment]
nope we do not need `ParentDocumentId`, `DocumentId` is what we should use
