### ISSUE TITLE
Prepare for v0.1.0 release

### ISSUE THREAD

**Issue by rsjethani** [ioki-mobility/go-outline#36]
Polish API and CLI and update docs

**Comment by StefMa** [comment]
I am already on it by rewriting the Readme. Will create a  PR soon

**Comment by rsjethani** [comment]
You didn't created an issue first ;)

I will stop my work then...I had some modifications in mind...but will add later then

**Comment by StefMa** [comment]
Sorry 😞 

However, we could also add some documentation to the Go package 🙂 
Above this line:
https://github.com/ioki-mobility/go-outline/blob/4bf018c9998aca9fee1be333048e860f44d5ca61/client.go#L1
I just found it out that it works 😁
