### ISSUE TITLE
Use cobra to generate cli docs 

### ISSUE THREAD

**Issue by StefMa** [ioki-mobility/go-outline#46]
See also this discussion:
https://github.com/ioki-mobility/go-outline/discussions/44

For now we want to have simple and straightforward. Just generate the docs in markdown and put into the repo "somehow".

We could also think here about an GH Action that runs each time something in /cli changes, generate the docs and push to the branch to the /clisdocs directory or something...

**Comment by rsjethani** [comment]
IMO no need to go down that rabbit hole. Lets keep it simple: PR creator and reviewers make sure that if a PR touches CLI app behavior then cli docs are also updated as part of the PR.

Now what would be our cli docs?
This would be the auto-generated output into a CLI.md in the root directory. The README just gives a short overview of the cli app with a few examples then points to CLI.md for more details.
