### ISSUE TITLE
Feature: Create document on Outline

### ISSUE THREAD

**Issue by StefMa** [ioki-mobility/go-outline#5]
> An example would be the ADRs. I want to keep them in the Github repo, so we have all the versioning and PR goodness. However, I would like to use Outline to publish them to make them more accessible for others.
Every time a file is changed, I want to do something like `outline publish my_text.md` in the CI pipeline to publish the markdown file from the ADR repo as a read-only Outline document.

**Comment by rsjethani** [comment]
I think title is too specific for a general purpose repo. IMHO it should be "Feature: Create document" etc.

**Comment by StefMa** [comment]
Decided that to use this issues as "affects-api" and therefore was fixed via #20.
Because it is also already merged, I changed the milestone to [v0.1.0](https://github.com/ioki-mobility/go-outline/milestone/1)

CLI implemented will be tracked via #42
